# Site settings
title: DZ Blog
SEOTitle: 德志的博客 | DZ Blog
header-img: img/post-bg-desk.jpg
email: a-liudezhi@gmail.com
description: "Every failure is leading towards success."
keyword: "DZ, DZ Blog,  德志的博客, liudezhi, iOS, Apple, iPhone"
url: "https://a-liudezhi.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/a-liudezhi/a-liudezhi.github.io.git" # you code repository

# Sidebar settings  侧边栏是响应式布局的，当屏幕尺寸小于992px时侧边栏就移动到底部。见bootstrap栅格系统 http://v3.bootcss.com/css/
sidebar: true                           # whether or not using Sidebar.添加侧边栏
sidebar-about-description: "Goals determine what you going to be!"   #  简单的描述一下你自己
sidebar-avatar: /img/about-DZ-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
# 你的大头贴，请使用绝对地址.注意：名字区分大小写！后缀名也是


# SNS settings
RSS: false
# weibo_username:
zhihu_username:     liudezhi
github_username:    a-liudezhi
facebook_username:  liudezhi
jianshu_username:   1f26360ad0ca
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10      # 一页你准备放几篇文章
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]   # 分页插件
gems:
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# more info please open https://github.com/gitalk/gitalk

gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e99d4df98b703b84c748                            #生成的clientID
  clientSecret: 07c1e0aecedda49f5d23f0200117878e8f045a99  #生成的clientSecret
  repo: a-liudezhi.github.io    #存储你评论 issue 的 Github 仓库名
  owner: a-liudezhi    # github用户名
  admin: a-liudezhi    # github用户名 这个仓库的管理员，可以有多个，用数组表示，一般写自己
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68
#
#  Google Analytics
#  ga_track_id: 'UA-144640959-1'            # Format: UA-xxxxxx-xx
#  ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

highlighter: rouge


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "logdown",
        href: "http://liudezhi.logdown.com/"
    },{
        title: "简书·DZ",
        href: "https://www.jianshu.com/u/1f26360ad0ca"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
